-- group A AND GROUP B
INSERT INTO T_Q3 ( EXP )
SELECT MF.EXP as all_exp FROM CLINICAL_FACT CF INNER JOIN MICROARRAY_FACT MF ON CF.S_ID=MF.S_ID WHERE CF.S_ID IN ( 
	SELECT DISTINCT S_ID FROM CLINICAL_FACT WHERE P_ID IN (
   		SELECT P_ID FROM CLINICAL_FACT WHERE DS_ID IN (SELECT DS_ID FROM DISEASE WHERE NAME='ALL')) AND S_ID IS NOT NULL
	);

SELECT * FROM T_Q3;

INSERT INTO T_Q3_2 ( EXP )
SELECT MF.EXP as not_all_exp FROM CLINICAL_FACT CF INNER JOIN MICROARRAY_FACT MF ON CF.S_ID=MF.S_ID WHERE CF.S_ID IN ( 
	SELECT DISTINCT S_ID FROM CLINICAL_FACT WHERE P_ID IN (
   		SELECT P_ID FROM CLINICAL_FACT WHERE DS_ID IN (SELECT DS_ID FROM DISEASE WHERE NAME<>'ALL')) AND S_ID IS NOT NULL
	);

SELECT * FROM T_Q3_2;

SELECT STATS_T_TEST_PAIRED(T_Q3.EXP, T_Q3_2.EXP) t_observed
FROM T_Q3, T_Q3_2;


